# Generated by Django 5.0.3 on 2024-04-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_txtfiles_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txtfiles',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
